apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: hello-world-multicluster
  labels:
    workflows.argoproj.io/archive-strategy: "false"
    workflows.argoproj.io/enable-ocm-multicluster: "true" # enable OCM multicluster
  annotations:
    workflows.argoproj.io/ocm-placement: "workflow-placement" # evaluate the OCM Placement
    workflows.argoproj.io/description: |
      This is a simple hello world example.
      You can also run it in Python: https://couler-proj.github.io/couler/examples/#hello-world
spec:
  entrypoint: whalesay
  templates:
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["hello world"]
