kind: Deployment
apiVersion: apps/v1
metadata:
  name: argoworkflow-install-addon
  namespace: open-cluster-management
  labels:
    app: argoworkflow-install-addon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argoworkflow-install-addon
  template:
    metadata:
      labels:
        app: argoworkflow-install-addon
    spec:
      serviceAccountName: argoworkflow-install-addon-sa
      containers:
      - name: argoworkflow-install-addon
        image: quay.io/open-cluster-management/argo-workflow-multicluster:latest
        imagePullPolicy: IfNotPresent
        command:
          - /install-addon
        args:
          - "controller"
